name: aura_patient
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: any
  firebase_database: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
   - assets/heart.png
   - assets/spo2.png
   - assets/profile.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/MontserratExtraBold.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/MontserratSemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
